[project]
name = "imageembedding"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "mediapipe>=0.10.21",
    "urllib3>=2.5.0",
]
